repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
        exclude: ^\.bumpversion\.cfg$
    -   id: end-of-file-fixer
        exclude: ^\.bumpversion\.cfg$
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
